Repository pi-hole/PADD, pull requests merged in 2022-12, with the labels that each got.

#277 Fix dhcp_ipv6_heatmap on mega
  padd.sh
Labels: PR: ready for review

#281 Add version info to slim
  padd.sh
Labels: PR: ready for review

#280 Remove special handling of certain upstream DNS server
  padd.sh
Labels: PR: ready for review

#272 Re-order network info in mini
  padd.sh
Labels: PR: Approved

#274 Use /etc/pihole/versions file to gather version information
  padd.sh
Labels: PR: Approved

#282 Reduce punctuation
  padd.sh
Labels: PR: Approved

#283 Add space between Tx and Rx
  padd.sh
Labels: PR: Approved

#269 PADD v3.9.0
  .github/workflows/codespell.yml
  .github/workflows/editorconfig-checker.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  padd.sh
Labels: PR: ready for review

#292 Use github cli to sync master back to development
  .github/workflows/sync-back-to-dev.yml
Labels: Internal, PR: ready for review

#300 Try to reduce flickering
  padd.sh
Labels: Bugfix

#301 Bump version to v3.9.1
  padd.sh
Labels: PR: ready for review

#302 Don't use hashes to check for updates on master
  padd.sh
Labels: Bugfix

#304 Fix check if FTL is running
  padd.sh
Labels: Bugfix, PR: ready for review

#291 Add merge conflict workflow
  .github/workflows/merge-conflict.yml
Labels: PR: ready for review

#296 Explicitly test for sysinfo files
  padd.sh
Labels: Bugfix

#309 Shorten no merge conflict message
  .github/workflows/merge-conflict.yml
Labels: internal, PR: ready for review

#312 Fix status message
  padd.sh
Labels: PR: ready for review

#310 Don't use zero to signal failure
  padd.sh
Labels: PR: ready for review

#313 Use `getFTLPID` instead of `pidof`
  padd.sh
Labels: PR: ready for review

#320 Bump version to v3.10.0
  padd.sh
Labels: PR: ready for review
