Repository pi-hole/PADD, pull requests merged in 2023-01, with the labels that each got.

#323 Add action to close stale PR
  .github/workflows/stale_pr.yml
Labels: internal

#316 Add version bump workflow
  .github/workflows/version_bump.yml
Labels: Internal, PR: Approval Required

#330 Change labels in workflows
  .github/workflows/stale.yml
  .github/workflows/stale_pr.yml
  .github/workflows/sync-back-to-dev.yml
Labels: Internal, PR: Master Branch

#335 Export LOCALE
  padd.sh
Labels: PR: Approval Required

#322 PADD v3.10.1
  .github/workflows/codespell.yml
  .github/workflows/editorconfig-checker.yml
  .github/workflows/sync-back-to-dev.yml
  README.md
  padd.sh
Labels: Release
